routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// 

Route::get('displayAntecedenteAnt/search', 'DisplayAntecedenteAntController@buscar');
Route::resource('displayAntecedenteAnt','DisplayAntecedenteAntController');

Route::get('displayAntecedente/search', 'DisplayAntecedenteController@buscar');
Route::resource('displayAntecedente','DisplayAntecedenteController');

Route::get('displayCambio/search', 'DisplayCambioController@buscar');
Route::resource('displayCambio','DisplayCambioController');

Route::get('displayDocumento/search', 'DisplayDocumentoController@buscar');
Route::resource('displayDocumento','DisplayDocumentoController');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin|Editor']], function() {
    
    Route::get('/roles/search', 'RoleController@buscar');
    Route::resource('roles','RoleController');

    Route::get('users/search', 'UserController@buscar');
    Route::resource('users','UserController');

    Route::get('permissions/search', 'PermissionController@buscar');
    Route::resource('permissions','PermissionController');

    Route::get('productos/search', 'ProductoController@buscar');
    Route::resource('productos','ProductoController');

    Route::get('documentos/search', 'DocumentoController@buscar');
    Route::resource('documentos','DocumentoController');

    Route::get('segmentos/search', 'SegmentoController@buscar');
    Route::resource('segmentos','SegmentoController');

    Route::get('secciones/search', 'SeccionController@buscar');
    Route::resource('secciones','SeccionController');

    Route::get('seccionCambios/back/{id}', 'SeccionCambioController@atras');
    Route::get('seccionCambios/search', 'SeccionCambioController@buscar');
    Route::resource('seccionCambios','SeccionCambioController');


    Route::get('cambios/search', 'CambiosController@buscar');
    Route::resource('cambios','CambiosController');
    
    Route::get('antecedentes/back/{id}', 'AntecedentesController@atras');
    Route::get('antecedentes/search', 'AntecedentesController@buscar');
    Route::post('antecedentes/editar/{id}', 'AntecedentesController@editar');
    Route::resource('antecedentes','AntecedentesController');

    Route::get('ChildAntecedentes/search', 'ChildAntecedentesController@buscar');
    Route::post('ChildAntecedentes/editar/{id}', 'ChildAntecedentesController@editar');
    Route::get('ChildAntecedentes/back/{id}', 'ChildAntecedentesController@atras');
    Route::resource('ChildAntecedentes','ChildAntecedentesController');
    
    
});



// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function () {
    return view('home');
});

Route::get('/inicio', function () {
    
    return view('home');
});

Route::get('/test', function () {
    return view('test');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/DisplayCambioController.php
<?php
namespace App\Http\Controllers;
use Auth;
use Illuminate\Http\Request;
use App\Documento;
use App\Segmento;
use App\cambio;
use App\User;
use DB;

class DisplayCambioController extends Controller
{

   
    
    public function show($id)
    {
    
        $seccion = DB::table('seccionCambio')->where('id', $id)->get();
        $seccion = $seccion[0];
        $cambios= DB::table('cambios')->where('id_seccion', $id)->get();
        $antecedentes = array();
        $categorias = array();
        foreach($cambios as $camb){

            $p = DB::table('cambio_antecedente')->where('id_cambio', $camb->id)->select('id_antecedente')->get();
            $antecedentes1 = array();
            if(sizeof($p) >0 ){
                $antecedentes1[] = $camb->id;
                foreach($p as $hijo)
                {
                    $ant =DB::table('antecedenteCambios')->where('id', $hijo->id_antecedente)->get();
                    $antecedentes1[] = $ant[0];
                    // $cont++;
                }
            $antecedentes[] = $antecedentes1;
            $cat =array();
                    
                    foreach($antecedentes1 as $ant){
                        if((String)gettype($ant) != 'integer'){
                            $cat[]= $ant->id;
                            $categoriaA = DB::table('categoriaantecedentes')->where('id_antecedente',$ant->id)->select('categoria')->get();
                            $categoriaAs = array();
                           for($i =0;$i< sizeof($categoriaA);$i++)
                            {
                                $categoriaAs[] = $categoriaA[$i]->categoria;
                            }
                            // dd($categorias);
                            $cat[] = $categoriaAs;
                        }
                       
                    }
                    $categorias[] = $cat;
            }
        }
       
        // dd(($categorias));
        
         
        return view('displayCambio.show',compact('seccion','cambios','antecedentes','cat'));
    }
}

resources/views/displayCambio/show.blade.php
<?php ?>
@extends('layouts.app')

@section('content')

<?php  function cita($ante){
    $nueva;
    $rest = substr($ante->Fecha, -2);
    //consultiva
    if($ante->Serie == "A"){

        $nueva = $ante->Nombre . '. Opinión Consultiva OC-'.$ante->Numero.'/'.$rest.'.';
    }

    //contenciosa
    if($ante->Serie == "C"){
        $nueva = $ante->Nombre . " v. " .$ante->Contra .'. '.$ante->Tipo .'.';
    }

    //otra
    if($ante->Serie == "W"){
        $nueva = $ante->explicacion.'. '.$ante->Nombre . '. ';
    }
    return $nueva; 
} ?>
    <div class="container">
    <a id="back" href="{{  url('admin/seccionCambios/back/'.$seccion->id_secPadre) }}" class="previous round">&#8249;</a>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Informacion Documento</div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Título</label>
                            {{ $seccion->Titulo }}
                        </div>


                        
                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Autor</label>
                            {{ $seccion->Autor }}
                        </div>
                     
                        <div class="form-group">
                           
                            <br>
                            <br>
                            <div class ="conDiv">
                            <?php echo htmlspecialchars_decode( $seccion->Contenido_html) ?>
                            </div>
                        </div>
                        <?php $contador =0; ?>
                       
                        @foreach ($antecedentes as $ant )
                         <?php $tag1 = 'cam'.(string) $ant[0]; ?>
                            
                            <div id = "{{$tag1}}"  class="referencia" >
                                   
                                   @for ($i =1; $i< sizeof($ant);$i++)
                                        
                                        <a style="color:white;"  href="{{ route('displayAntecedente.show',$ant[0]) }}">
                                   <h5>  {{$i}}.&nbsp; <?php $comp = cita($ant[$i]); echo $comp; ?><br></h5> </a>
                                   @endfor
                                  
                            </div>

                                <script> 
                                        var num = <?php echo $ant[0] ?>;
                                        var nom = '#t'+num;
                                        var nom2 = '#'+ "{{$tag1}}";


                                                tippy(nom, {
                                                    html: document.querySelector(nom2),
                                                    delay: 25,
                                                        flip: true,
                                                        arrow: true,
                                                        arrowType: 'round',
                                                        size: 'large',
                                                        interactive: true,
                                                        interactiveBorder: 5,
                                                  
                                                    })
                                                    </script>
                                
                          <?php $contador++ ?>          
                        @endforeach
                    </div>
                </div>
              
            </div>
        </div>
    </div>

@endsection