routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// 

Route::get('displayAntecedenteAnt/search', 'DisplayAntecedenteAntController@buscar');
Route::resource('displayAntecedenteAnt','DisplayAntecedenteAntController');

Route::get('displayAntecedente/search', 'DisplayAntecedenteController@buscar');
Route::resource('displayAntecedente','DisplayAntecedenteController');

Route::get('displayCambio/search', 'DisplayCambioController@buscar');
Route::resource('displayCambio','DisplayCambioController');

Route::get('displayDocumento/search', 'DisplayDocumentoController@buscar');
Route::resource('displayDocumento','DisplayDocumentoController');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin|Editor']], function() {
    
    Route::get('/roles/search', 'RoleController@buscar');
    Route::resource('roles','RoleController');

    Route::get('users/search', 'UserController@buscar');
    Route::resource('users','UserController');

    Route::get('permissions/search', 'PermissionController@buscar');
    Route::resource('permissions','PermissionController');

    Route::get('productos/search', 'ProductoController@buscar');
    Route::resource('productos','ProductoController');

    Route::get('documentos/search', 'DocumentoController@buscar');
    Route::resource('documentos','DocumentoController');

    Route::get('segmentos/search', 'SegmentoController@buscar');
    Route::resource('segmentos','SegmentoController');

    Route::get('secciones/search', 'SeccionController@buscar');
    Route::resource('secciones','SeccionController');

    Route::get('seccionCambios/back/{id}', 'SeccionCambioController@atras');
    Route::get('seccionCambios/search', 'SeccionCambioController@buscar');
    Route::resource('seccionCambios','SeccionCambioController');


    Route::get('cambios/search', 'CambiosController@buscar');
    Route::resource('cambios','CambiosController');
    
    Route::get('antecedentes/back/{id}', 'AntecedentesController@atras');
    Route::get('antecedentes/search', 'AntecedentesController@buscar');
    Route::post('antecedentes/editar/{id}', 'AntecedentesController@editar');
    Route::resource('antecedentes','AntecedentesController');

    Route::get('ChildAntecedentes/search', 'ChildAntecedentesController@buscar');
    Route::post('ChildAntecedentes/editar/{id}', 'ChildAntecedentesController@editar');
    Route::get('ChildAntecedentes/back/{id}', 'ChildAntecedentesController@atras');
    Route::resource('ChildAntecedentes','ChildAntecedentesController');
    
    
});



// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function () {
    return view('home');
});

Route::get('/inicio', function () {
    
    return view('home');
});

Route::get('/test', function () {
    return view('test');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/SeccionCambioController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Support\Facades\Input;
use Auth;
use Illuminate\Http\Request;
use App\Documento;
use App\Segmento;
use App\Seccione;
use App\Cambio;
use App\User;
use DB;

class SeccionCambioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
        // $secciones = Seccione::orderBy('id','DESC')->paginate(10);
        $secciones = DB::table('seccioncambios')->orderBy('id','DESC')->get();
       
        return view('secciones.index',compact('secciones'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $documento = Input::get('titulo'); 
        $iden = Input::get('padre');  
        $seccionPadre =  DB::table('secciones')->where('id', $iden)->where('Titulo', $documento)->select()->get();
        $seccionPadre = $seccionPadre[0];
        // dd($seccionPadre);
        return view('seccionCambios.create',compact('seccionPadre')); //return the view with the list of roles passed as an array
      
    }
    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'Titulo' => 'required|max:255',
            'tipo' => 'required',
            'Titulo_Padre'=>'required',
            'Contenido'=>'required'

        ]);
        $id_padre = intval($request->padre);
        $documento = $request->only('Titulo_Padre');
        $seccionID =  DB::table('secciones')->where('id', $id_padre)->where('Titulo', $documento)->select('id')->get();
        // dd($seccionID);
        $nombre = Auth::user()->name;
        $id = Auth::user()->id;
        $texto = $request->Contenido;
        
        $patron = '#<span class="CADH">(.*?)</span>#s';
        $filtro =   preg_match_all ($patron, $texto, $matches);
        $tclean = strip_tags($texto);
        // dd($tclean);
        $idnuevo = "";
      
            DB::beginTransaction();
            $idnuevo = DB::table('seccioncambio')->insertGetId(
                ['id_SecPadre'=>$seccionID[0]->id,'Titulo'=> $request->Titulo , 'tipo'=>$request->tipo, 'Contenido'=>$tclean,'Contenido_html'=>$request->Contenido, 'added_by'=> $id, 'Autor'=>$request->Autor ]
            );
            DB::commit();
    
        // dd($matches[1]);
        if(sizeof($matches[0]) == 0)
        {

        }else{
            $pos =0;
            for ($i = 0 ; $i<sizeof($matches[1]);$i++){
                $cam = html_entity_decode($matches[1][$i], ENT_QUOTES, 'UTF-8');
                // dd($cam);
                DB::beginTransaction();
               $idCambio=  DB::table('cambios')->insertGetId(
                    ['id_autor' => $id,'id_seccion'=>$idnuevo,'Titulo'=> $cam, 'Contenido'=>$cam ]
                );
                $mystring = $texto;
                $findme   = 'class="CADH"';
                $pos2 = strpos($mystring, $findme,$pos + strlen($findme)); 
                $pos = $pos2;
                $texto = substr_replace($mystring,"id='t".$idCambio."'",$pos,0);
                DB::table('seccioncambio')
                ->where('id', $idnuevo)
                ->update(['Contenido_html' => $texto]);
                DB::commit();
            }
        }
       
        return redirect()->route('documentos.index')
            ->with('success','Segmento-Cambio creato exitosamente');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
    
        $seccion = DB::table('seccioncambio')->where('id', $id)->get();
        $seccion = $seccion[0];
        $cambios= DB::table('cambios')->where('id_seccion', $id)->get();
    
         
        return view('seccionCambios.show',compact('seccion','cambios'));
    }

    public function atras($id){
        
        
        $seccion =  DB::table('secciones')->where('id', $id)->get();


        $cambios =  DB::table('seccioncambio')->where('id_secPadre', $id)->get();
        $seccion =$seccion[0];
        $secCambios = array();
        foreach($cambios as $cambio)
        {
            $hijos_id =  DB::table('seccioncambio')->where('id', $cambio->id)->get();
            
            array_push($secCambios, $hijos_id[0]);

        }
         
        return view('secciones.show',compact('seccion','secCambios'));
        
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $seccion = DB::table('seccioncambio')->where('id', $id)->select('id')->get();
        // $documentos = Documento::get();
        //dd($documentos);
       
        return view('seccionCambio.edit',compact('seccion'));
  
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'Titulo' => 'required|max:255',
            'tipo' => 'required',
            'documentos'=> 'required'
        ]);

        $id_doc = $request->only('documentos');
        $titulo = $request->only('Titulo');
        $tipo = $request->only('tipo');

        $documento = Documento::find($id_doc)->first();
        //dd($documento->id);
        
        DB::table('segmentos')
            ->where('id', $id)
            ->update(['documento_id' => $documento->id,'documento_titulo'=> $documento->Titulo,'Titulo'=>$request->Titulo,'tipo'=>$request->tipo[0]]);
        
        return redirect()->route('seccionCambios.index')
            ->with('success','Segmento modificado exitosamente');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        Segmento::find($id)->delete();
        return redirect()->route('segmentos.index')
            ->with('success','Segmento eliminado exitosamente ');
    }

    public function buscar(Request $request)
    {
       

        // Gets the query string from our form submission 
            $query = $request->input('search');
            // Returns an array of articles that have the query string located somewhere within 
            // our articles titles. Paginates them so we can break up lots of search results.
            $segmentos = DB::table('segmentos')->where('Titulo', 'LIKE', '%' . $query . '%')->paginate(10);

         
                
            // returns a view and passes the view the list of articles and the original query.
            return view('segmentos.index',compact('segmentos'))
            ->with('i', ($request->input('page', 1) - 1) * 5);

          
    }
}

resources/views/seccionCambios/create.blade.php
<?php ?>
@extends('layouts.app')

@section('content')
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
<script>

tinymce.init({
  selector: 'textarea',
  height: 500,
  plugins: ['advlist autolink lists link image charmap print preview anchor textcolor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code help wordcount'],
   // toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tinymce.com/css/codepen.min.css'],
    formats: {
    alignleft: {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes : 'left'},
    aligncenter: {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes : 'center'},
    alignright: {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes : 'right'},
    alignjustify: {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes : 'full'},
  
    underline: {inline : 'span', 'classes' : 'underline', exact : true},
   
    forecolor: {inline : 'span', classes : 'forecolor', styles : {color : '%value'}},
    hilitecolor: {inline : 'span', classes : 'hilitecolor', styles : {backgroundColor : '%value'}},
    custom_format: {block : 'h1', attributes : {title : 'Header'}, styles : {color : 'red'}}
  },
  style_formats: [
    { title: 'Cambio', inline: 'span',classes: 'CADH'},
 
  ],
//   formats: {
//     alignleft: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'left' },
//     aligncenter: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'center' },
//     alignright: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'right' },
//     alignfull: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'full' },
//     bold: { inline: 'span', 'classes': 'bold' },
//     italic: { inline: 'span', 'classes': 'italic' },
//     underline: { inline: 'span', 'classes': 'underline', exact: true },
//     strikethrough: { inline: 'del' },
//     customformat: { inline: 'span', styles: { color: '#00ff00', fontSize: '20px' }, attributes: { title: 'My custom format' }, classes: 'example1' },
//   }
});
</script>

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Crear nueva Seccion</div>
                    {{ $seccionPadre->id }}
                    
                    <div class="panel-body">
                        <!-- Display Validation Errors -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" role="form" method="POST" action="{{ url('admin/seccionCambios') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('Titulo') ? ' has-error' : '' }}">
                                <label for="Titulo" class="col-md-4 control-label">Titulo</label>

                                <div class="col-md-6">
                                    <input id="Titulo" type="text" class="form-control" name="Titulo" value="{{ old('Titulo') }}" placeholder="Titulo"
                                           required autofocus>

                                    @if ($errors->has('Titulo'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('Titulo') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('Titulo_Padre') ? ' has-error' : '' }}">
                                <label for="Titulo_Padre" class="col-md-4 control-label">Seccion Original</label>

                                <div class="col-md-6">
                                    <input id="Titulo_Padre" type="text" class="form-control" name="Titulo_Padre" value="{{ $seccionPadre->Titulo}}"  
                                           required autofocus readonly>

                                    @if ($errors->has('Titulo_Padre'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('Titulo_Padre') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('Autor') ? ' has-error' : '' }}">
                                <label for="Autor" class="col-md-4 control-label">Autor</label>

                                <div class="col-md-6">
                                    <input id="Autor" type="text" class="form-control" name="Autor" value="{{ old('Autor') }}"  placeholder="Autor"
                                           required autofocus >

                                    @if ($errors->has('Autor'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('Autor') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group{{ $errors->has('tipo') ? ' has-error' : '' }}">
                            <label for="tipo" class="col-md-4 control-label">Tipos</label>

                            <div class="col-md-6">
                                <select id="tipos" name="tipo"  class="form-control">
                               
                                        <option value="Articulo">Articulo</option>
                                        <option value="Comentario">Ley</option>
                              
                                </select>


                                @if ($errors->has('tipo'))
                                    <span class="help-block">
                                    <strong>{{ $errors->first('tipo') }}</strong>
                                </span>
                                @endif
                            </div>
                           

                           <div style="padding:50px;">
                           <input id="padre" type="text" class="form-control" name="padre" value="{{ $seccionPadre->id }}" 
                                           style="display:none;" >
                            <textarea  id="Contenido" name="Contenido">
                                {{$seccionPadre->Contenido}}
                            </textarea>
                            </div>
                            <br>
                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Save
                                    </button>

                                    <a class="btn btn-link" href="{{ url('admin/users') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/seccionCambios/index.blade.php
<?php ?>
@extends('layouts.app')

@section('content')
    <div class="container">
    
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Secciones Management</div>

                    <div class="panel-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        {!! Form::open(['method'=>'GET','url'=>'admin\secciones\search','class'=>'row','role'=>'search'])  !!}
                        
                    <div id="custom-search-input">
                                            <div class="input-group col-md-12">
                                                <input type="text" name ="search" class="  search-query form-control" placeholder="Search" />
                                                <span class="input-group-btn">
                                                    <button class="btn btn-danger" type="submit">
                                                        <span class=" glyphicon glyphicon-search"></span>
                                                    </button>
                                                </span>
                                            </div>
                                        </div>
                       
                     
                        {!! Form::close() !!}
                        @if(sizeof($secciones) >0 )  
                        <table class="table table-striped table-bordered table-condensed">
                      
                       
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Titulo</th>
                                <th>Tipo</th>
                                <th>Documento Padre</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach ($secciones as $key => $seccion)
                                                
                                <tr class="list-users">
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $seccion->Titulo }} 
                                    <button class="btn" title='{{$seccion->Titulo }} '>Text</button>
                                        <script>
                                        tippy('.btn')
                                        </script>
                                    </td>
                                    <td>{{ $seccion->Tipo }}</td>
                                    <td></td>
                                   
                                    <td>
                                        <a class="btn btn-info" href="{{ route('secciones.show',$seccion->id) }}">Show</a>
                                        <a class="btn btn-primary" href="{{ route('secciones.edit',$seccion->id) }}">Edit</a>

                                        <form action="{{ url('admin/secciones/'.$seccion->id) }}" method="POST" style="display: inline-block">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}

                                            <button type="submit" id="delete-task-{{ $seccion->id }}" class="btn btn-danger">
                                                <i class="fa fa-btn fa-trash"></i>Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        @else
                        <h2> No hay resultados </h2>
                        <br>
                        @endif
                        <a href="{{ route('secciones.create') }}" class="btn btn-success">New Seccion</a>
                        <a href="{{ route('secciones.index') }}" class="btn btn-info">Ver todo</a>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/seccionCambios/show.blade.php
<?php ?>
@extends('layouts.app')

@section('content')
    <div class="container">
    <a id="back" href="{{  url('admin/seccionCambios/back/'.$seccion->id_secPadre) }}" class="previous round">&#8249;</a>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Informacion Documento</div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Título</label>
                            {{ $seccion->Titulo }}
                        </div>

                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Tipo</label>
                            {{ $seccion->Tipo }}
                        </div>

                        
                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Autor</label>
                            {{ $seccion->Autor }}
                        </div>
                     
                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Contenido</label>
                            <br>
                            <br>
                            <div class ="conDiv">
                            <?php echo htmlspecialchars_decode( $seccion->Contenido_html) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php $i =0; ?>
                @if(sizeof($cambios) >0 )  
                @if(sizeof($cambios) >0 )  
                        <h2 >Listado de Cambios </h2>
                        <table class="table table-striped table-bordered table-condensed">
                      
                       
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Titulo</th>
                               
                                <!-- <th>Autor</th> -->
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $contador =0 ?>
                            @foreach ($cambios as $key => $cambio)
                                                
                                <tr class="list-users">
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $cambio->Titulo }} 
                                
                                    </td>
                                    
                                   
                                    <!-- <td>{{ $cambio->id_autor }}</td> -->
                                   
                                    <td>
                                        <a class="btn btn-info" href="{{ route('cambios.show',$cambio->id) }}">Show</a>
                                        <a class="btn btn-primary" href="{{ route('antecedentes.show',$cambio->id) }}">Administrar</a>
                                       
                                    </td>
                                    @role('admin')
                                    <td>
                                        <form action="{{ url('admin/cambios/'.$cambio->id) }}" method="POST" style="display: inline-block">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}

                                            <button type="submit" id="delete-task-{{ $cambio->id }}" class="btn btn-danger">
                                                <i class="fa fa-btn fa-trash"></i>Delete
                                            </button>
                                        </form>
                                    </td>
                                    @endrole
                                </tr>
                                <?php $contador++ ?>
                            @endforeach
                            </tbody>
                        </table>
                        
                        @else
                        <h2> No hay resultados </h2>
                        <br>
                        @endif
                
                
                @endif
            </div>
        </div>
    </div>

@endsection