routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// 

Route::get('displayAntecedenteAnt/search', 'DisplayAntecedenteAntController@buscar');
Route::resource('displayAntecedenteAnt','DisplayAntecedenteAntController');

Route::get('displayAntecedente/search', 'DisplayAntecedenteController@buscar');
Route::resource('displayAntecedente','DisplayAntecedenteController');

Route::get('displayCambio/search', 'DisplayCambioController@buscar');
Route::resource('displayCambio','DisplayCambioController');

Route::get('displayDocumento/search', 'DisplayDocumentoController@buscar');
Route::resource('displayDocumento','DisplayDocumentoController');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin|Editor']], function() {
    
    Route::get('/roles/search', 'RoleController@buscar');
    Route::resource('roles','RoleController');

    Route::get('users/search', 'UserController@buscar');
    Route::resource('users','UserController');

    Route::get('permissions/search', 'PermissionController@buscar');
    Route::resource('permissions','PermissionController');

    Route::get('productos/search', 'ProductoController@buscar');
    Route::resource('productos','ProductoController');

    Route::get('documentos/search', 'DocumentoController@buscar');
    Route::resource('documentos','DocumentoController');

    Route::get('segmentos/search', 'SegmentoController@buscar');
    Route::resource('segmentos','SegmentoController');

    Route::get('secciones/search', 'SeccionController@buscar');
    Route::resource('secciones','SeccionController');

    Route::get('seccionCambios/back/{id}', 'SeccionCambioController@atras');
    Route::get('seccionCambios/search', 'SeccionCambioController@buscar');
    Route::resource('seccionCambios','SeccionCambioController');


    Route::get('cambios/search', 'CambiosController@buscar');
    Route::resource('cambios','CambiosController');
    
    Route::get('antecedentes/back/{id}', 'AntecedentesController@atras');
    Route::get('antecedentes/search', 'AntecedentesController@buscar');
    Route::post('antecedentes/editar/{id}', 'AntecedentesController@editar');
    Route::resource('antecedentes','AntecedentesController');

    Route::get('ChildAntecedentes/search', 'ChildAntecedentesController@buscar');
    Route::post('ChildAntecedentes/editar/{id}', 'ChildAntecedentesController@editar');
    Route::get('ChildAntecedentes/back/{id}', 'ChildAntecedentesController@atras');
    Route::resource('ChildAntecedentes','ChildAntecedentesController');
    
    
});



// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function () {
    return view('home');
});

Route::get('/inicio', function () {
    
    return view('home');
});

Route::get('/test', function () {
    return view('test');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Segmento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Segmento extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'documento_id','Titulo','tipo', 'documento_titulo',
    ];
}

app/Http/Controllers/SegmentoController.php
<?php
namespace App\Http\Controllers;
use Auth;
use Illuminate\Http\Request;
use App\Documento;
use App\Segmento;
use App\Seccion;
use App\Cambio;
use App\User;
use DB;

class SeccionesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $segmentos = Segmento::orderBy('id','DESC')->paginate(10);
        return view('secciones.index',compact('segmentos'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $documentos = Documento::pluck('Titulo','id');
        return view('secciones.create',compact('documentos')); //return the view with the list of roles passed as an array
      // return view('segmentos.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */

     //funcion para guardar las secciones de cambio dentro de un articulo
    public function store(Request $request)
    {
        $this->validate($request, [
            'Titulo' => 'required|max:255',
            'tipo' => 'required',
            'documentos'=>'required',
            'Contenido'=>'required'

        ]);
        $docID = $request->only('documentos');
        $documento = Documento::find($docID)->first();
        
        //nombre guardados en la sesion 
        $nombre = Auth::user()->name;
        $id = Auth::user()->id;
        $texto = $request->Contenido;

        //se separa del string completo la parte que contiene dicho tag
        // $matches contiene todos los segmentos con cambios
        $patron = '#<span class="CADH">(.*?)</span>#s';
        $filtro =   preg_match_all ($patron, $texto, $matches);

       // se incerta el cambio
        DB::beginTransaction();
        DB::table('segmentos')->insert(
            ['documento_id' => $documento->id, 'documento_titulo'=>$documento->Titulo,'Titulo'=> $request->Titulo , 'tipo'=>$request->tipo, 'contenido'=>$request->Contenido, 'id_Autor'=> $id, 'NombreAutor'=>$nombre ]
        );

        //obtengo el el id del ultimo insert         
        $id_seg =  DB::table('segmentos')->where('documento_id', $documento->id)->where('Titulo', $request->Titulo)->select('id')->get();
        //agrego los cambios a la base de datos 
        for ($i = 0 ; $i<sizeof($matches[1]);$i++){
            $cam = html_entity_decode($matches[1][$i], ENT_QUOTES, 'UTF-8');
           
            DB::table('cambios')->insert(
                ['id_autor' => $id,'id_segmento'=>$id_seg[0]->id,'Titulo'=> $cam, 'Contenido'=>$cam ]
            );
        }
        
        DB::commit();
        return redirect()->route('secciones.index')
            ->with('success','Segmento creato exitosamente');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $segmento = Segmento::find($id);
        return view('secciones.show',compact('segmento'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $segmento = Segmento::find($id);
        $documentos = Documento::get();
        //dd($documentos);
       
        return view('secciones.edit',compact('segmento','documentos'));
  
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'Titulo' => 'required|max:255',
            'tipo' => 'required',
            'documentos'=> 'required'
        ]);

        $id_doc = $request->only('documentos');
        $titulo = $request->only('Titulo');
        $tipo = $request->only('tipo');

        $documento = Documento::find($id_doc)->first();
        //dd($documento->id);
        
        DB::table('segmentos')
            ->where('id', $id)
            ->update(['documento_id' => $documento->id,'documento_titulo'=> $documento->Titulo,'Titulo'=>$request->Titulo,'tipo'=>$request->tipo[0]]);
        
        return redirect()->route('secciones.index')
            ->with('success','Segmento modificado exitosamente');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        Segmento::find($id)->delete();
        return redirect()->route('secciones.index')
            ->with('success','Segmento eliminado exitosamente ');
    }

    public function buscar(Request $request)
    {
       

        // Gets the query string from our form submission 
            $query = $request->input('search');
            // Returns an array of articles that have the query string located somewhere within 
            // our articles titles. Paginates them so we can break up lots of search results.
            $segmentos = DB::table('segmentos')->where('Titulo', 'LIKE', '%' . $query . '%')->paginate(10);

         
                
            // returns a view and passes the view the list of articles and the original query.
            return view('secciones.index',compact('segmentos'))
            ->with('i', ($request->input('page', 1) - 1) * 5);

          
    }
}

resources/views/segmentos/create.blade.php
<?php ?>
@extends('layouts.app')

@section('content')
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
<script>

tinymce.init({
  selector: 'textarea',
  height: 500,
  plugins: ['advlist autolink lists link image charmap print preview anchor textcolor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code help wordcount'],
   // toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tinymce.com/css/codepen.min.css'],
  
  style_formats: [
    { title: 'Red text', inline: 'span',classes: 'CADH'},
 
  ],
//   formats: {
//     alignleft: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'left' },
//     aligncenter: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'center' },
//     alignright: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'right' },
//     alignfull: { selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'full' },
//     bold: { inline: 'span', 'classes': 'bold' },
//     italic: { inline: 'span', 'classes': 'italic' },
//     underline: { inline: 'span', 'classes': 'underline', exact: true },
//     strikethrough: { inline: 'del' },
//     customformat: { inline: 'span', styles: { color: '#00ff00', fontSize: '20px' }, attributes: { title: 'My custom format' }, classes: 'example1' },
//   }
});
</script>

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Crear nuevo segmento</div>
                    {{ $iden}}
                    <div class="panel-body">
                        <!-- Display Validation Errors -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" role="form" method="POST" action="{{ url('admin/segmentos') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('Titulo') ? ' has-error' : '' }}">
                                <label for="Titulo" class="col-md-4 control-label">Titulo</label>

                                <div class="col-md-6">
                                    <input id="Titulo" type="text" class="form-control" name="Titulo" value="{{ old('Titulo') }}"
                                           required autofocus>

                                    @if ($errors->has('Titulo'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('Titulo') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('tipo') ? ' has-error' : '' }}">
                            <label for="tipo" class="col-md-4 control-label">Tipos</label>

                            <div class="col-md-6">
                                <select id="tipos" name="tipo">
                               
                                        <option value="Articulo">Articulo</option>
                                        <option value="Comentario">Ley</option>
                              
                                </select>


                                @if ($errors->has('tipo'))
                                    <span class="help-block">
                                    <strong>{{ $errors->first('tipo') }}</strong>
                                </span>
                                @endif
                            </div>

                           


                            <div class="form-group{{ $errors->has('documentos') ? ' has-error' : '' }}">
                                <label for="documentos" class="col-md-4 control-label">Documento padre</label>

                                <div class="col-md-6">
                                    <select id="documento" name="documentos[]" multiple>
                                    @foreach ($documentos as $key => $documento)
                                            <option value="{{$key}}">{{$documento}}</option>
                                    @endforeach
                                    </select>


                                    @if ($errors->has('documentos'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('documentos') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                                
                            <textarea  id="Contenido" name="Contenido">

                            </textarea>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Save
                                    </button>

                                    <a class="btn btn-link" href="{{ url('admin/users') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/segmentos/edit.blade.php
<?php ?>

@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Editar Segmento</div>

                    <div class="panel-body">
                        <!-- Display Validation Errors -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> Existio un problema con los datos ingresados <br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif


                        <form class="form-horizontal" role="form" method="POST"
                              action="{{ url('admin/segmentos/'.$segmento->id) }}">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}

                            <div class="form-group{{ $errors->has('Titulo') ? ' has-error' : '' }}">
                            <label for="Titulo" class="col-md-4 control-label">Titulo</label>

                            <div class="col-md-6">
                                <input id="Titulo" type="text" class="form-control" name="Titulo" 
                                value="{{$segmento->Titulo}}" required autofocus>

                                @if ($errors->has('Titulo'))
                                    <span class="help-block">
                                    <strong>{{ $errors->first('Titulo') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>



                            
                            <div class="form-group{{ $errors->has('tipo') ? ' has-error' : '' }}">
                                <label for="tipo" class="col-md-4 control-label">Tipo</label>

                                <div class="col-md-6">

                                    <select id="tipo" name="tipo[]" multiple>
                                     
                                          
                                                <option value="Carta" >Carta</option>
                                                <option value="Ley">Ley</option>
                                           
                                      
                                    </select>

                                    @if ($errors->has('tipo'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('tipo') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                         

                            <div class="form-group{{ $errors->has('documentos') ? ' has-error' : '' }}">
                                <label for="documentos" class="col-md-4 control-label">Documento Padre</label>

                                <div class="col-md-6">

                                    <select id="documento" name="documentos[]" multiple>
                                        @foreach ($documentos as $documento)
                                            <option value="{{$documento->id}}" >
                                                {{$documento->Titulo}}
                                            </option>
                                        @endforeach
                                    </select>

                                    @if ($errors->has('documentos'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('documentos') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>

                                    <a class="btn btn-link" href="{{ url('admin/segmentos') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/segmentos/index.blade.php
<?php ?>
@extends('layouts.app')

@section('content')
    <div class="container">
    
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Segmentos Management</div>

                    <div class="panel-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                        {!! Form::open(['method'=>'GET','url'=>'admin\segmentos\search','class'=>'row','role'=>'search'])  !!}
                        
                    <div id="custom-search-input">
                                            <div class="input-group col-md-12">
                                                <input type="text" name ="search" class="  search-query form-control" placeholder="Search" />
                                                <span class="input-group-btn">
                                                    <button class="btn btn-danger" type="submit">
                                                        <span class=" glyphicon glyphicon-search"></span>
                                                    </button>
                                                </span>
                                            </div>
                                        </div>
                       
                     
                        {!! Form::close() !!}
                        @if(sizeof($segmentos) >0 )  
                        <table class="table table-striped table-bordered table-condensed">
                      
                       
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Titulo</th>
                                <th>Tipo</th>
                                <th>Documento Padre</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach ($segmentos as $key => $segmento)
                                                
                                <tr class="list-users">
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $segmento->Titulo }} 
                                    <button class="btn" title='{{$segmento->Titulo }} '>Text</button>
                                        <script>
                                        tippy('.btn')
                                        </script>
                                    </td>
                                    <td>{{ $segmento->tipo }}</td>
                                    <td>{{ $segmento->documento_titulo }}</td>
                                   
                                    <td>
                                        <a class="btn btn-info" href="{{ route('segmentos.show',$segmento->id) }}">Show</a>
                                        <a class="btn btn-primary" href="{{ route('segmentos.edit',$segmento->id) }}">Edit</a>

                                        <form action="{{ url('admin/segmentos/'.$segmento->id) }}" method="POST" style="display: inline-block">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}

                                            <button type="submit" id="delete-task-{{ $segmento->id }}" class="btn btn-danger">
                                                <i class="fa fa-btn fa-trash"></i>Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        @else
                        <h2> No hay resultados </h2>
                        <br>
                        @endif
                        <a href="{{ route('segmentos.create') }}" class="btn btn-success">New Segmento</a>
                        <a href="{{ route('segmentos.index') }}" class="btn btn-info">Ver todo</a>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/segmentos/show.blade.php
<?php ?>
@extends('layouts.app')

@section('content')
    <div class="container">
  
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Informacion Documento</div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Título</label>
                            {{ $segmento->Titulo }}
                        </div>

                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Tipo</label>
                            {{ $segmento->tipo }}
                        </div>

                        
                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Documento Padre</label>
                            {{ $segmento->documento_titulo }}
                        </div>
                     
                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Contenido</label>
                            <?php echo htmlspecialchars_decode( $segmento->Contenido) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection