routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// 

Route::get('displayAntecedenteAnt/search', 'DisplayAntecedenteAntController@buscar');
Route::resource('displayAntecedenteAnt','DisplayAntecedenteAntController');

Route::get('displayAntecedente/search', 'DisplayAntecedenteController@buscar');
Route::resource('displayAntecedente','DisplayAntecedenteController');

Route::get('displayCambio/search', 'DisplayCambioController@buscar');
Route::resource('displayCambio','DisplayCambioController');

Route::get('displayDocumento/search', 'DisplayDocumentoController@buscar');
Route::resource('displayDocumento','DisplayDocumentoController');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin|Editor']], function() {
    
    Route::get('/roles/search', 'RoleController@buscar');
    Route::resource('roles','RoleController');

    Route::get('users/search', 'UserController@buscar');
    Route::resource('users','UserController');

    Route::get('permissions/search', 'PermissionController@buscar');
    Route::resource('permissions','PermissionController');

    Route::get('productos/search', 'ProductoController@buscar');
    Route::resource('productos','ProductoController');

    Route::get('documentos/search', 'DocumentoController@buscar');
    Route::resource('documentos','DocumentoController');

    Route::get('segmentos/search', 'SegmentoController@buscar');
    Route::resource('segmentos','SegmentoController');

    Route::get('secciones/search', 'SeccionController@buscar');
    Route::resource('secciones','SeccionController');

    Route::get('seccionCambios/back/{id}', 'SeccionCambioController@atras');
    Route::get('seccionCambios/search', 'SeccionCambioController@buscar');
    Route::resource('seccionCambios','SeccionCambioController');


    Route::get('cambios/search', 'CambiosController@buscar');
    Route::resource('cambios','CambiosController');
    
    Route::get('antecedentes/back/{id}', 'AntecedentesController@atras');
    Route::get('antecedentes/search', 'AntecedentesController@buscar');
    Route::post('antecedentes/editar/{id}', 'AntecedentesController@editar');
    Route::resource('antecedentes','AntecedentesController');

    Route::get('ChildAntecedentes/search', 'ChildAntecedentesController@buscar');
    Route::post('ChildAntecedentes/editar/{id}', 'ChildAntecedentesController@editar');
    Route::get('ChildAntecedentes/back/{id}', 'ChildAntecedentesController@atras');
    Route::resource('ChildAntecedentes','ChildAntecedentesController');
    
    
});



// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function () {
    return view('home');
});

Route::get('/inicio', function () {
    
    return view('home');
});

Route::get('/test', function () {
    return view('test');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/AntecedentesController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Support\Facades\Input;
use Auth;
use Illuminate\Http\Request;
use App\Documento;
use App\Segmento;
use App\antecedenteCambio;
use App\cambio;
use App\User;
use Carbon\Carbon;
use DB;

class AntecedentesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $cambios = cambio::orderBy('id','DESC')->paginate(10);
        $documento = array();
        $segmento = array();
        foreach($cambios as $cambio){
            $id_seg =  DB::table('seccioncambio')->where('id', $cambio->id_seccion)->select('Titulo')->get();
            
            array_push($segmento, $id_seg[0]->Titulo);
            // array_push($documento, $id_seg[0]->id_seccion);
        }
        return view('cambios.index',compact('cambios','segmento'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $idPadre = Input::get('iden'); 
        // dd($idPadre);

        $padre  =  DB::table('cambios')->where('id',(int) $idPadre)->get();
         
 
        $padre = $padre[0]->id;
        return view('antecedentes.create',compact('padre'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $this->validate($request, [
            'serie' => 'required|max:255',
            'nombre' => 'required|max:400',
            'tipo' => 'required',
            'numero' => 'required|max:50',
            'padre' => 'required|max:255',
            'fecha' => 'required|max:255',
            'detalle' => 'required|max:8000',
            'categorias'=>'required',
            'corte'=> 'required'
    
        ]);
        
        // $contra = $request->contra;
        //  dd($request->categorias[1]);
        $padre  =  DB::table('cambios')->where('id',$request->padre)->get();
        $padre_id = $padre[0]->id;
        $detalle = $request->detalle;
       
        
        if($detalle =="@[vacio]"){
            $detalle ="";
        }


        if($request->tipo =="@[vacio]"){
            $request->tipo ="";
        }

        if($request->parrafo =="@[vacio]"){
            $request->parrafo ="";
        }
       
        
        $newId = DB::table('antecedentecambios')
        ->insertGetId(['Nombre'=> $request->nombre,'Detalle'=> $detalle,'Fecha'=> $request->fecha, 'serie' =>$request->serie,
        'Tipo'=> $request->tipo, 'Numero'=>$request->numero,'Contra'=>$request->contra,'Contenido_Html'=>$request->detalle,'Fecha'=>$request->fecha,
        'Parrafo'=>$request->parrafo,'Corte'=>$request->corte,'added_by'=>Auth::user()->id,'created_at'=>Carbon::now()->format('Y-m-d H:i:s'),'explicacion'=>$request->explicacion]);
        
        DB::table('cambio_antecedente')->insert(['id_cambio'=>$padre_id,'id_antecedente'=>$newId]);
        // dd($newId);
        foreach ($request->input('categorias') as $key => $value) {
           DB::table('categoriaantecedentes')->insert(['id_antecedente'=>$newId,'categoria'=>$value,'added_by'=>Auth::user()->id,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')]);
        }

        // return redirect()->route('documentos.index')
        // ->with('success','Segmento modificado exitosamente');
        $cambio = cambio::find($padre_id);
        $ar  =  DB::table('seccioncambio')->where('id', $cambio->id_seccion)->select('Titulo','id','Autor')->get();
        $secTitulo = $ar[0]->Titulo;
        $documento = $ar[0]->id;
        $autor = $ar[0]->Autor;
        $p = DB::table('cambio_antecedente')->where('id_cambio', $padre_id)->select('id_antecedente')->get();
        $antecedentes = array();
        if(sizeof($p) >0 ){
            foreach($p as $hijo)
            {
                $ant =DB::table('antecedentecambios')->where('id', $hijo->id_antecedente)->get();
                $antecedentes[] = $ant[0];
            }
            
        }


        return view('antecedentes.show',compact('cambio','secTitulo','antecedentes','autor','documento'))->with('success','Antecedente eliminado exitosamente');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        
        $cambio = cambio::find($id);
        $ar  =  DB::table('seccioncambio')->where('id', $cambio->id_seccion)->select('Titulo','id','Autor')->get();
        $secTitulo = $ar[0]->Titulo;
        $documento = $ar[0]->id;
        $autor = $ar[0]->Autor;
        $p = DB::table('cambio_antecedente')->where('id_cambio', $id)->select('id_antecedente')->get();
        $antecedentes = array();
        if(sizeof($p) >0 ){
            foreach($p as $hijo)
            {
                $ant =DB::table('antecedentecambios')->where('id', $hijo->id_antecedente)->get();
                $antecedentes[] = $ant[0];
            }
            
        }
        
        // dd($antecedentes);


        return view('antecedentes.show',compact('cambio','secTitulo','antecedentes','autor','documento'));
    }

    public function atras($id){
        // dd($id);
      

        $seccion = DB::table('seccioncambio')->where('id', $id)->get();
        $seccion = $seccion[0];
        // $cam= DB::table('cambio_antecedente')->where('id_cambio', $seccion->id)->get();
        $cambios = DB::table('cambios')->where('id_seccion', $id)->get();
         
        return view('seccioncambios.show',compact('seccion','cambios'));

    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $antecedente  =  DB::table('antecedentecambios')->where('id',$id)->get();
        $p = DB::table('cambio_antecedente')->where('id_antecedente',$id)->get();
        $padre = DB::table('cambios')->where('id',$p[0]->id_cambio)->get();
        $padre = $padre[0]->id;
        $categoria = DB::table('categoriaantecedentes')->where('id_antecedente',$id)->select('categoria')->get();
        $categorias = array();
       for($i =0;$i< sizeof($categoria);$i++)
        {
            $categorias[] = $categoria[$i]->categoria;
        }
        $antecedente = $antecedente[0];
    //    dd(sizeof($categorias));
        return view('antecedentes.edit',compact('antecedente','categorias','padre'));
  
    }

    // public function administrar($id)
    // {
    //     $cambio = cambio::find($id);
    //     $segmento = Documento::find($cambio->id_segmento);
    //     //dd($documentos);
       
    //     return view('antecedentes.show',compact('segmento','cambio'));
  
    // }
    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */

    public function editar(Request $request,$id){
        
        $this->validate($request, [
            'serie' => 'required|max:255',
            'nombre' => 'required|max:400',
            'tipo' => 'required',
            'numero' => 'required|max:2000',
            'padre' => 'required|max:255',
            'fecha' => 'required|max:200',
            'detalle' => 'required|max:8000',
            'categorias'=>'required',
            'corte'=> 'required'
    
        ]);

        $padre  =  DB::table('cambios')->where('id',$request->padre)->get();
        $padre_id = $padre[0]->id;
        $detalle = $request->detalle;
       
        if($detalle =="@[vacio]"){
            $detalle ="";
        }

    
        if($request->tipo =="@[vacio]"){
            $request->tipo ="";
        }

        if($request->parrafo =="@[vacio]"){
            $request->parrafo ="";
        }

        $newId = DB::table('antecedentecambios')->where('id', $id)
        ->update(['Nombre'=> $request->nombre,'Detalle'=> $detalle,'Fecha'=> $request->fecha, 'serie' =>$request->serie,
        'Tipo'=> $request->tipo, 'Numero'=>$request->numero,'Contra'=>$request->contra,'Contenido_Html'=>$request->detalle,'Fecha'=>$request->fecha,
        'Parrafo'=>$request->parrafo,'Corte'=>$request->corte,'updated_by'=>Auth::user()->id,'updated_at'=>Carbon::now()->format('Y-m-d H:i:s'),'explicacion'=>$request->explicacion]);
        
        // dd($request->input('categorias'));
        DB::table('categoriaantecedentes')->where('id_antecedente',$id)->delete();
        foreach ($request->input('categorias') as $key => $value) {
           DB::table('categoriaantecedentes')->insert(['id_antecedente'=>$id,'categoria'=>$value,'added_by'=>Auth::user()->id,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')]);
           
        }

        // return redirect()->route('documentos.index')
        // ->with('success','Segmento modificado exitosamente');
        $cambio = cambio::find($padre_id);
        $ar  =  DB::table('seccioncambio')->where('id', $cambio->id_seccion)->select('Titulo','id','Autor')->get();
        $secTitulo = $ar[0]->Titulo;
        $documento = $ar[0]->id;
        $autor = $ar[0]->Autor;
        $p = DB::table('cambio_antecedente')->where('id_cambio', $padre_id)->select('id_antecedente')->get();
        $antecedentes = array();
        if(sizeof($p) >0 ){
            foreach($p as $hijo)
            {
                $ant =DB::table('antecedentecambios')->where('id', $hijo->id_antecedente)->get();
                $antecedentes[] = $ant[0];
            }
            
        }


        return view('antecedentes.show',compact('cambio','secTitulo','antecedentes','autor','documento'))->with('success','Antecedente eliminado exitosamente');

    }
    public function update(Request $request, $id)
    {
        // dd($request);
        // $this->validate($request, [
        //     'Titulo' => 'required|max:255',
        //     'PAT' => 'required',
        //     'PAC' => 'required',

resources/views/antecedentes/show.blade.php
<?php ?>
@extends('layouts.app')

@section('content')
    <div class="container">
      <a id="back" href="{{  url('admin/antecedentes/back/'.$cambio->id_seccion) }}" class="previous round">&#8249;</a>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Informacion Antecedente antecedente</div>

                    <div class="panel-body">
                   

                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Título</label>
                            {{ $cambio->Titulo }}
                        </div>
                
                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Autor</label>
                            {{ $autor }}
                        </div>
                     
                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Contenido</label>
                            <br>
                            <br>
                            <div class ="conDiv">
                            <?php echo htmlspecialchars_decode( $cambio->Contenido) ?>
                            </div>
                        </div>
                       
                    </div>
                </div>
                <?php $i =0; ?>

                @if(sizeof($antecedentes) >0 )  
                        <h2 >Listado de antecedentes </h2>
                        <table class="table table-striped table-bordered table-condensed">
                      
                       
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Nombre</th>
                               
                                <!-- <th>Autor</th> -->
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $contador =0 ?>
                            @foreach ($antecedentes as $key => $antecedente)
                                                
                                <tr class="list-users">
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $antecedente->Nombre }} 
                                
                                    </td>
                                    
                                   
                                    <!-- <td>{{ $cambio->id_autor }}</td> -->
                                   
                                    <td>
                                        <!-- <a class="btn btn-info" href="{{ route('antecedentes.show',$antecedente->id) }}">Show</a> -->
                                        <a class="btn btn-info" href="{{ route('ChildAntecedentes.show',[$antecedente->id,'hijo1'=>$cambio->id]) }}">Administrar</a>
                                        <a class="btn btn-primary" href="{{ route('antecedentes.edit',$antecedente->id) }}">Edit</a>
                                    </td>
                                    @role('admin')<td>
                                        <form action="{{ url('admin/antecedentes/'.$antecedente->id) }}" method="POST" style="display: inline-block">
                                        <input id="padre" type="text" class="form-control" name="padre" value="{{$cambio->id}}" style="display:none"
                                           required autofocus>
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}

                                            <button type="submit" id="delete-task-{{ $antecedente->id }}" class="btn btn-danger">
                                                <i class="fa fa-btn fa-trash"></i>Delete
                                            </button>
                                        </form>
                                  </td>  @endrole
                                </tr>
                                <?php $contador++ ?>
                            @endforeach
                            </tbody>
                        </table>
                        @else
                        <h2> No hay antecedentes </h2>
                        <br>
                        @endif
                      
                        <a href="{{ route('antecedentes.create', ['iden'=>$cambio->id]) }}" class="btn btn-success">Nuevo Antecedente</a>
                        
                
            
            </div>
        </div>
    </div>

@endsection